### PR TITLE
DF-3364 Add new active profile for OS monitoring

### PR DESCRIPTION
**Pull request by mdavidovski**
- The release branch this will be needed for is https://github.com/alv-ch/alv-onlineform-service/compare/release/df-3364-add-monitoring-for-npa
- Take a look if I need to add some specific logging level = DEBUG for Onlineformservice
- And in the release branch in os, take a look if something else would be useful to log. For now, I just log the method, arguments, and time spent in each method

### CODE REVIEW

**Review by seco-mgabor — COMMENTED** [review]
Where is the logic related to this new profile?

**Comment by mdavidovski** [comment]
> Where is the logic related to this new profile?

In the branch link on my previous comment, https://github.com/alv-ch/alv-onlineform-service/compare/release/df-3364-add-monitoring-for-npa. I that what you mean?

**Comment by seco-mgabor** [comment]
Yes, exactly. :)

**Comment by mdavidovski** [comment]
Actually, the feature branch would be a better option, https://github.com/alv-ch/alv-onlineform-service/tree/feature/df-3364-add-monitoring-for-npa

**Review by emina-str — APPROVED** [review]

**Pull request merged**
